"""Signup update

Revision ID: 09cb3f303406
Revises: 249b35b24d84
Create Date: 2026-03-27 00:25:11.129701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09cb3f303406'
down_revision: Union[str, None] = '249b35b24d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
